spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java-0909-002?serverTimezone=UTC
    username: root
    password: WSLG456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true